### ISSUE TITLE
Wrong items in inventory

### ISSUE THREAD

**Issue by celishere** [SunProxy/sun#15]
With a proxy:
![image](https://user-images.githubusercontent.com/54947469/105038388-4ecfa480-5a70-11eb-8a1b-b5a3fce971be.png)

Without a proxy:
![image](https://user-images.githubusercontent.com/54947469/105038565-89d1d800-5a70-11eb-9780-6b3de0a1fc1f.png)

**Comment by Jviguy** [comment]
Was this after transferring or just in general?

**Comment by Jviguy** [comment]
I'm reopening this as of now just because I don't know for sure the latest pr fixed this given issue. Because you never really answered my question.

**Comment by celishere** [comment]
> Was this after transferring or just in general?

After

**Comment by Jviguy** [comment]
Ok can you give the newest version a try cause I think I resolved that issue with the pr.

**Comment by Kris-Driv** [comment]
thanks

**Comment by celishere** [comment]
The problem is solved. Good job.
