### ISSUE TITLE
The idea: The ability to show the load on the proxy using the command

### ISSUE THREAD

**Issue by celishere** [SunProxy/sun#19]
Add a command /status with which you can find out the number of players connected to the proxy and its load

**Comment by Jviguy** [comment]
I like this idea I'll probably add this soon as a optional command

**Comment by Jviguy** [comment]
This is closed as of now with the latest commit which pushes the changes. Keep in mind that the cmd returns the current usage of the whole given device rather than the process as I couldn't anything to good for Process usage tracking.

**Comment by celishere** [comment]
Good job!
